[build]
 # command = "cd exampleSite && hugo --gc --minify -D -b $URL"
 command = "hugo --gc --minify -D -b $URL"
 # publish = "exampleSite/public"
 publish = "public"
[build.environment]
HUGO_VERSION = "0.118.2"
HUGO_THEMESDIR = "../.."
# HUGO_THEME = "repo"
TZ = "Europe/Paris"

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify -D -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc --minify -D -b $DEPLOY_PRIME_URL"
